import {
  Virginia,
  UGH,
  Fruits,
  Bratz,
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
  salvatore,
  spotify,
  dora,
  manWolf,
  boneHeart,
  weeknd,
  taylor,
  song,
  office,
  oneForAll,
  colorQuote,
  swiftie,
  
} from "../assets/images/index";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "contact",
  },
  {
    _id: 1005,
    title: "Journal",
    link: "/journal",
  },
];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: "201",
    img: Virginia,
    productName: "Virginia Wolf Quote",
    price: "300",
    color: "Blank and White",
    badge: true,
    des: "Virginia Wolf quote saying for most of history Anonymous was a woman",
  },
  {
    _id: "202",
    img: UGH,
    productName: "UGH",
    price: "250",
    color: "Gray",
    badge: true,
    des: "Simple Text spelling UGH",
  },
  {
    _id: "203",
    img: Fruits,
    productName: "Fruits Desigm",
    price: "250",
    color: "White",
    badge: true,
    des: "A maze alternating between pink coloured squares and fruits",
  },
  {
    _id: "204",
    img: Bratz,
    productName: "Bratz",
    price: "325",
    color: "Red",
    badge: true,
    des: "A unique coloured bag with a text bratz",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

export const paginationItems = [
  {
    _id: 1001,
    img: salvatore,
    productName: "Salvatore Brothers Quote",
    price: "250",
    color: "Black",
    badge: true,
    des: "A quote saying Don't be stupid that girl is with the Salvatore Brothers",
  },
  {
    _id: 1002,
    img: UGH,
    productName: "UGH",
    price: "250",
    color: "Black",
    badge: true,
    des: "Simple text UGH",
  },
  {
    _id: 1003,
    img: taylor,
    productName: "Taylor's Version",
    price: "300",
    color: "Off-White",
    badge: true,
    des: "A simple bag with Taylor's Version inside brackets",
  },
  {
    _id: 1004,
    img: weeknd,
    productName: "The Weeknd",
    price: "280",
    color: "White",
    badge: true,
    des: "",
  },
  {
    _id: 1005,
    img: bestSellerOne,
    productName: "Heart",
    price: "500",
    color: "Black",
    badge: true,
    des: "An aesthetic Flowershaped pink Heart",
  },
  {
    _id: 1006,
    img: bestSellerTwo,
    productName: "Mixed Grafitti",
    price: "550",
    color: "Off-White",
    badge: false,
    des: "A mix of logos of various top brands",
  },
  {
    _id: 1007,
    img: bestSellerThree,
    productName: "Wanted",
    price: "300",
    color: "Golden and White",
    badge: true,
    des: "Wanted Message written for Monkey D. Luffy.",
  },
  {
    _id: 1008,
    img: bestSellerFour,
    productName: "Omoni",
    price: "300",
    color: "Black",
    badge: false,
    des: "Omoni written in a unique font style giving it an aesthetic look",
  },
  {
    _id: 1009,
    img: newArrOne,
    productName: "Children's Bag",
    price: "200",
    color: "White",
    badge: true,
    des: "A Tote Bag specially designed for Children with Attractive Stickers.",
  },
  {
    _id: 1010,
    img: newArrTwo,
    productName: "Eatable Themed Bag",
    price: "250",
    color: "White",
    badge: true,
    des: "A Unique Tote Bag with images of various breads.",
  },
  {
    _id: 1011,
    img: newArrThree,
    productName: "Flowers and a Quote",
    price: "350",
    color: "Off-White",
    badge: true,
    des: "",
  },
  {
    _id: 1012,
    img: newArrFour,
    productName: "The Readers Theme",
    price: "380",
    color: "White",
    badge: false,
    des: "Various readers with a book in their windows",
  },
  {
    _id: 1013,
    img: song,
    productName: "Piano Letters",
    price: "250",
    color: "Off-White",
    badge: false,
    des: "A sequence of piano lyrics with letters",
  },

  {
    _id: 1014,
    img: Virginia,
    productName: "Virginia Wolf Quote",
    price: "300",
    color: "Black",
    badge: true,
    des: "Virginia Wolf quote saying for most of history Anonymous was a woman",
  },
  {
    _id: 1015,
    img: Bratz,
    productName: "Bratz",
    price: "325",
    color: "Red",
    badge: false,
    des: "A red coloured tote bag with a word bratz written in an aesthetic way",
  },
  {
    _id: 1016,
    img: spotify,
    productName: "Here comes the sun",
    price: "250",
    color: "Off-White",
    badge: true,
    des: "A spotify cover of the song Here comes the sun by the Beatles",
  },
  {
    _id: 1017,
    img: Fruits,
    productName: "Fruits Design",
    price: "250",
    color: "White",
    badge: false,
    des: "A maze alternating between pink coloured squares and fruits",
  },
  {
    _id: 1018,
    img: colorQuote,
    productName: "Color Quote",
    price: "400",
    color: "Off-White",
    badge: true,
    des: "A colourful picture with a hidden quote.",
  },
  {
    _id: 1019,
    img: office,
    productName: "The Office",
    price: "250",
    color: "Black",
    badge: true,
    des: "All characters from the famous tv series the office",
  },
  {
    _id: 1020,
    img: swiftie,
    productName: "Taylor Swift",
    price: "280",
    color: "White",
    badge: true,
    des: "A simple quote saying I am written and direccted by Taylor Swift.",
  },
  {
    _id: 1021,
    img: boneHeart,
    productName: "BoneHeart",
    price: "350",
    color: "Off-White",
    badge: true,
    des: "A heart resembled by boney fingers.",
  },
  {
    _id: 1022,
    img: manWolf,
    productName: "Man Wolf",
    price: "220",
    color: "Black",
    badge: true,
    des: "A man with the head of a wolf",
  },
  {
    _id: 1023,
    img: dora,
    productName: "Little Girl",
    price: "350",
    color: "Off-White",
    badge: true,
    des: "Face of a smiling little girl",
  },
  {
    _id: 1024,
    img: oneForAll,
    productName: "Anime",
    price: "400",
    color: "Black",
    badge: true,
    des: "A character from a famous anime.",
  },
 

  
  
];
// =================== PaginationItems End here =================
